In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [3]:
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
#reading the dataset

df = pd.read_csv('spam.csv')

In [5]:
#first five records

df.head()

Class                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
#row and col count

df.shape

(5572, 2)

In [7]:
#counting the number of spam & ham

spam_ham = df['Class'].value_counts()
spam_ham

ham     4825
spam     747
Name: Class, dtype: int64

In [8]:
#percentage of spam in the dataset

(spam_ham[1]/float(spam_ham[0]+spam_ham[1])) * 100

13.406317300789663

In [9]:
#creating label column- by mapping the class such that spam-1 and ham-0

df['label'] = df['Class'].map({'spam':1,'ham':0})

In [10]:
df.head()

Class                                            message  label
0   ham  Go until jurong point, crazy.. Available only ...      0
1   ham                      Ok lar... Joking wif u oni...      0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...      1
3   ham  U dun say so early hor... U c already then say...      0
4   ham  Nah I don't think he goes to usf, he lives aro...      0

In [11]:
#selecting x and y

x = df['message']
y = df['Class']

In [12]:
#feature

x

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: message, Length: 5572, dtype: object

In [13]:
#label

y

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: Class, Length: 5572, dtype: object

In [15]:
pip install sklearn from skl

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement from (from versions: none)
ERROR: No matching distribution found for from

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:
#importing library

from sklearn.model_selection import train_test_split

ModuleNotFoundError: No module named 'sklearn'

In [18]:
#train test split with test size = 30%

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

NameError: name 'train_test_split' is not defined

In [ ]:
#importing Counvectorization from sklearn

from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
#Instantiate CountVectorizer with stop_words -vect is an object of class CountVectorizer()

vect = CountVectorizer(stop_words='english')

In [ ]:
# fit vect on the feature (X_train) -  converts a corpus of documents into a vector of unique words

x=vect.fit(x_train)
x

CountVectorizer(stop_words='english')

In [ ]:
#checkign the count of words in feature

x.vocabulary_

{'quite': 5026,
 'late': 3635,
 'lar': 3630,
 'ard': 944,
 '12': 260,
 'wun': 6908,
 'drivin': 2222,
 'tuesday': 6400,
 'night': 4330,
 'real': 5088,
 'chase': 1558,
 'run': 5321,
 'crossing': 1883,
 'street': 5910,
 'says': 5393,
 'answer': 890,
 'texts': 6158,
 'confirm': 1763,
 'deny': 2033,
 'work': 6865,
 'going': 2865,
 'small': 5676,
 'house': 3169,
 'think': 6195,
 'stop': 5894,
 'like': 3715,
 'hour': 3166,
 'roommate': 5289,
 'looking': 3796,
 'stock': 5885,
 'trip': 6370,
 'lol': 3782,
 'great': 2922,
 'im': 3253,
 'getting': 2819,
 'hungry': 3200,
 'good': 2877,
 'll': 3759,
 'phone': 4695,
 'tomo': 6295,
 'lunchtime': 3856,
 'shall': 5514,
 'organise': 4519,
 'yesterday': 6959,
 'true': 6379,
 'ya': 6932,
 'nice': 4323,
 'ready': 5087,
 'thursday': 6227,
 'hi': 3086,
 'way': 6714,
 '2day': 361,
 'normal': 4367,
 'ur': 6517,
 'unique': 6481,
 'hope': 3144,
 'know': 3570,
 'rest': 5223,
 'mylife': 4236,
 'wot': 6880,
 'lost': 3809,
 'today': 6277,
 'accept': 720,
 'day': 196

In [ ]:
#features named them separately as words

vect.get_feature_names()

C:\Users\fjwu\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090298926',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '07801543489',
 '07808247860',
 '07815296484',
 '07821230901',
 '07880867867',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '083',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700621170150p',
 '08701213

In [ ]:
#transformming feature - train & test set

x_train_transform = vect.transform(x_train)
x_test_transform = vect.transform(x_test)

In [ ]:
#x_train after transformation

x_train_transform.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
#x_test after transformation

x_test_transform.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 2, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
#shape of final train set

x_train_transform.shape

(3900, 7004)

In [ ]:
#printing  our final train set

print(x_train_transform)

  (0, 260)	1
  (0, 944)	1
  (0, 2222)	1
  (0, 3630)	1
  (0, 3635)	1
  (0, 5026)	1
  (0, 6908)	1
  (1, 4330)	1
  (1, 5088)	1
  (1, 6400)	1
  (2, 1558)	1
  (2, 1883)	1
  (2, 5321)	1
  (2, 5910)	1
  (3, 890)	1
  (3, 1763)	1
  (3, 2033)	1
  (3, 5393)	1
  (3, 6158)	1
  (4, 2865)	1
  (4, 3169)	1
  (4, 5676)	1
  (4, 6865)	1
  (5, 3166)	1
  (5, 3715)	1
  :	:
  (3895, 2278)	1
  (3895, 2892)	1
  (3895, 3086)	1
  (3895, 3734)	1
  (3895, 6836)	1
  (3895, 6852)	1
  (3896, 3638)	1
  (3896, 3759)	1
  (3896, 5752)	1
  (3897, 2712)	1
  (3897, 3049)	1
  (3897, 4852)	1
  (3897, 5099)	1
  (3897, 5756)	1
  (3897, 5757)	1
  (3898, 3464)	1
  (3898, 4387)	1
  (3898, 5482)	1
  (3898, 6286)	1
  (3899, 2081)	1
  (3899, 3493)	1
  (3899, 4250)	1
  (3899, 5389)	1
  (3899, 5724)	1
  (3899, 6076)	1


In [ ]:
#printing feature names

print(vect.get_feature_names())

['00', '000', '000pes', '008704050406', '0089', '0121', '01223585236', '01223585334', '02', '0207', '02072069400', '02073162414', '02085076972', '021', '03', '04', '0430', '05', '050703', '0578', '06', '07', '07008009200', '07046744435', '07090298926', '07099833605', '07123456789', '0721072', '07732584351', '07734396839', '07753741225', '0776xxxxxxx', '07781482378', '07786200117', '077xxx', '07801543489', '07808247860', '07815296484', '07821230901', '07880867867', '07946746291', '0796xxxxxx', '07973788240', '07xxxxxxxxx', '08', '0800', '08000407165', '08000776320', '08000839402', '08000930705', '08000938767', '08001950382', '08002888812', '08002986030', '08002986906', '08002988890', '08006344447', '0808', '08081263000', '08081560665', '0825', '083', '0844', '08448350055', '08448714184', '0845', '08450542832', '08452810071', '08452810073', '08452810075over18', '0870', '08700435505150p', '08700621170150p', '08701213186', '08701237397', '08701417012', '08701417012150p', '0870141701216', '

In [ ]:
#converting our x_train to dataframe with columns as vector's feature names

pd.DataFrame(x_train_transform.toarray(),columns=vect.get_feature_names())

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  02  \
0      0    0       0             0     0     0            0            0   0   
1      0    0       0             0     0     0            0            0   0   
2      0    0       0             0     0     0            0            0   0   
3      0    0       0             0     0     0            0            0   0   
4      0    0       0             0     0     0            0            0   0   
...   ..  ...     ...           ...   ...   ...          ...          ...  ..   
3895   0    0       0             0     0     0            0            0   0   
3896   0    0       0             0     0     0            0            0   0   
3897   0    0       0             0     0     0            0            0   0   
3898   0    0       0             0     0     0            0            0   0   
3899   0    0       0             0     0     0            0            0   0   

      0207  ...  zed  zeros  zhong  zindgi  zoe  zogtorius  zoom  zouk  zyada  \
0        0  ...    0      0      0       0    0          0     0     0      0   
1        0  ...    0      0      0       0    0          0     0     0      0   
2        0  ...    0      0      0       0    0          0     0     0      0   
3        0  ...    0      0      0       0    0          0     0     0      0   
4        0  ...    0      0      0       0    0          0     0     0      0   
...    ...  ...  ...    ...    ...     ...  ...        ...   ...   ...    ...   
3895     0  ...    0      0      0       0    0          0     0     0      0   
3896     0  ...    0      0      0       0    0          0     0     0      0   
3897     0  ...    0      0      0       0    0          0     0     0      0   
3898     0  ...    0      0      0       0    0          0     0     0      0   
3899     0  ...    0      0      0       0    0          0     0     0      0   

      èn  
0      0  
1      0  
2      0  
3      0  
4      0  
...   ..  
3895   0  
3896   0  
3897   0  
3898   0  
3899   0  

[3900 rows x 7004 columns]

In [1]:
#import BernoulliNB

from sklearn.naive_bayes import BernoulliNB

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
# instantiate bernoulli NB object

bnb = BernoulliNB()

In [ ]:
# fit model on training dataset

bnb.fit(x_train_transform,y_train)

BernoulliNB()

In [ ]:
#model prediction

y_pred = bnb.predict(x_test_transform)

In [ ]:
#model prediction probability

y_pred_proba = bnb.predict_proba(x_test_transform)

In [ ]:
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
#accuarcy score

metrics.accuracy_score(y_test,y_pred)

0.9736842105263158

In [ ]:
#confusion metrics

confusion = metrics.confusion_matrix(y_test,y_pred)
confusion

array([[1447,    1],
       [  43,  181]], dtype=int64)

In [ ]:
#Get True negative, False positive, False negative and True positive using confusion metrics

TN = confusion[0,0]
FP = confusion[0,1]
FN = confusion[1,0]
TP = confusion[1,1]

In [ ]:
# sensitivity using confusion metrics

sensitivity = TP/float(TP+FN)
sensitivity

0.8080357142857143

In [ ]:
#specificity using confusion metrics

specificity = TN/float(TN+FP)
specificity

0.9993093922651933

In [ ]:
#precision using confusion metrics

precision = TP/float(TP+FP)
precision

0.9945054945054945

In [ ]:
#classification report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.97      1.00      0.99      1448
        spam       0.99      0.81      0.89       224

    accuracy                           0.97      1672
   macro avg       0.98      0.90      0.94      1672
weighted avg       0.97      0.97      0.97      1672



In [ ]:
#importing library

from sklearn.naive_bayes import MultinomialNB

In [ ]:
# instantiate bernoulli NB object

mnb = MultinomialNB()


In [ ]:
# fit model on training dataset

mnb.fit(x_train_transform,y_train)

MultinomialNB()

In [ ]:
# predict class of y

y_pred = mnb.predict(x_test_transform)


In [ ]:
# predict probability on y

y_pred_proba = mnb.predict_proba(x_test_transform)

In [ ]:
# print accuracy score 

print(metrics.accuracy_score(y_test,y_pred))

0.9874401913875598


In [ ]:
# confusion metrics

confusion = metrics.confusion_matrix(y_test,y_pred)
confusion

array([[1438,   10],
       [  11,  213]], dtype=int64)

In [ ]:
#Get True negative, Flase positive, Flase negative and True positive using confusion metrics

TN = confusion[0,0]
FP = confusion[0,1]
FN = confusion[1,0]
TP = confusion[1,1]

In [ ]:
#Print Precision, recall, f1-score and support 

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.99      0.99      0.99      1448
        spam       0.96      0.95      0.95       224

    accuracy                           0.99      1672
   macro avg       0.97      0.97      0.97      1672
weighted avg       0.99      0.99      0.99      1672



In [ ]:
# import GaussianNB

from sklearn.naive_bayes import GaussianNB

In [ ]:
# instantiate bernoulli NB object

gnb = GaussianNB()

In [ ]:
# instantiate bernoulli NB object

gnb = GaussianNB()

In [ ]:
# fit model on training dataset

gnb.fit(x_train_transform.toarray(),y_train)

GaussianNB()

In [ ]:
# predict class of y

y_pred = gnb.predict(x_test_transform.toarray())

In [ ]:
# predict probability on y

y_pred_proba = gnb.predict_proba(x_test_transform.toarray())


In [ ]:
# print accuracy score 

print(metrics.accuracy_score(y_test,y_pred))

0.8953349282296651


In [ ]:
# get confusion metrics

confusion = metrics.confusion_matrix(y_test,y_pred)
confusion

array([[1285,  163],
       [  12,  212]], dtype=int64)

In [ ]:
#Get True negative, Flase positive, Flase negative and True positive using confusion metrics

TN = confusion[0,0]
FP = confusion[0,1]
FN = confusion[1,0]
TP = confusion[1,1]

In [ ]:
#Print Precision, recall, f1-score and support 

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.99      0.89      0.94      1448
        spam       0.57      0.95      0.71       224

    accuracy                           0.90      1672
   macro avg       0.78      0.92      0.82      1672
weighted avg       0.93      0.90      0.91      1672



In [ ]:
# print accuracy score of all three Naive Bayes algorithms.

print(metrics.accuracy_score(y_test,bnb.predict(x_test_transform.toarray())))
print(metrics.accuracy_score(y_test,mnb.predict(x_test_transform.toarray())))
print(metrics.accuracy_score(y_test,gnb.predict(x_test_transform.toarray())))

0.9736842105263158
0.9874401913875598
0.8953349282296651


In [ ]:
naive_bayes = MultinomialNB()
naive_bayes.fit(x_train_transform, y_train)

MultinomialNB()

In [ ]:
predection = naive_bayes.predict(x_test_transform)

In [ ]:
import pickle
pickle.dump(mnb, open('model.pkl', 'wb'))


In [ ]:
pickled_model = pickle.load(open('model.pkl', 'rb'))


In [ ]:
y_pred = pickled_model.predict(x_test_transform)

In [ ]:
print(metrics.accuracy_score(y_test,y_pred))

0.9874401913875598


In [ ]:
import joblib
joblib.dump(x,'transform.pkl')

['transform.pkl']

In [ ]:
from flask import Flask,render_template,url_for,request
import pickle
import joblib


filename = 'model.pkl'
clf = pickle.load(open(filename, 'rb'))
cv=pickle.load(open('transform.pkl','rb'))
app = Flask(__name__)

@app.route('/')
def home():
	return render_template('home.html')

@app.route('/predict',methods=['POST'])
def predict():
	if request.method == 'POST':
		message = request.form['message']
		data = [message]
		vect = cv.transform(data).toarray()
		my_prediction = clf.predict(vect)
	return render_template('result.html',prediction = my_prediction)

if __name__ == '__main__':
	app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
